"""The simulator: ten predictions in a row, about his own code.

Passing an exercise moves a node one rung. Only this moves it to `automático`,
and only if the ten survive an interval — a streak finished in one sitting is
short-term memory, which is exactly what this project is named after losing.

The questions are generated by making one small change to the file he wrote, and
the right answer is obtained by RUNNING the result. Nobody is asked what the code
does: a model's opinion is how 12550 once got accepted when the answer was 12750.
"""
from __future__ import annotations

import random
import re
from dataclasses import dataclass
from datetime import date

from .model import Course, Mastery
from .state import State
from .workspace import experimentar

SEGUIDAS_PARA_AUTOMATICO = 10

NUMERO = re.compile(r"(?<![\w.])(\d+)(?![\w.])")
COMPARADOR = re.compile(r"(<=|>=|<|>)")
TROCA = {"<": "<=", "<=": "<", ">": ">=", ">=": ">"}


@dataclass(frozen=True)
class Previsao:
    """One question. `saida_certa` came out of the machine, not out of a model."""

    pergunta: str
    codigo: str
    saida_certa: str
    mudanca: str


def _mudar_numero(codigo: str, i: int, rnd: random.Random) -> tuple[str, str] | None:
    achados = list(NUMERO.finditer(codigo))
    if i >= len(achados):
        return None
    m = achados[i]
    velho = int(m.group(1))
    novo = velho + rnd.choice((-1, 1, 1))
    if novo < 0:
        novo = velho + 1
    return (
        codigo[: m.start(1)] + str(novo) + codigo[m.end(1):],
        f"{velho} → {novo}",
    )


def _mudar_comparador(codigo: str, i: int, rnd: random.Random) -> tuple[str, str] | None:
    achados = list(COMPARADOR.finditer(codigo))
    if i >= len(achados):
        return None
    m = achados[i]
    novo = TROCA[m.group(1)]
    return (
        codigo[: m.start(1)] + novo + codigo[m.end(1):],
        f"{m.group(1)} → {novo}",
    )


MUTACOES = (_mudar_comparador, _mudar_numero)


def gerar(
    course: Course, nome: str, codigo: str, quantas: int = 1, semente: int | None = None
) -> list[Previsao]:
    """Small changes to his file, kept only when they run and change the output.

    A change that stops it running is thrown away: the question is 'what does this
    print', and 'it does not compile' teaches nothing about the limits of a loop.
    """
    rnd = random.Random(semente)
    corre, original = experimentar(course, nome, codigo)
    if not corre:
        return []

    candidatos = [(mut, i) for mut in MUTACOES for i in range(6)]
    rnd.shuffle(candidatos)

    previsoes: list[Previsao] = []
    vistos = {original.strip()}
    for mut, i in candidatos:
        if len(previsoes) >= quantas:
            break
        feito = mut(codigo, i, rnd)
        if feito is None:
            continue
        mutante, mudanca = feito
        if mutante == codigo:
            continue
        corre, saida = experimentar(course, nome, mutante)
        if not corre or saida.strip() in vistos:
            continue
        vistos.add(saida.strip())
        previsoes.append(Previsao(
            pergunta=f"Mudei uma coisa no teu {nome}: {mudanca}. O que é que ele escreve agora?",
            codigo=mutante,
            saida_certa=saida.strip(),
            mudanca=mudanca,
        ))
    return previsoes


def _normalizar(texto: str) -> str:
    return " ".join(texto.split())


def acertou(previsao: Previsao, resposta: str) -> bool:
    return _normalizar(resposta) == _normalizar(previsao.saida_certa)


def registar(state: State, node_id: str, certo: bool, hoje: date) -> str | None:
    """Returns the promotion, if this was the one that earned it.

    The streak has to cross a night: ten in one sitting is the same session
    answering itself, and that is not what `automático` is supposed to mean.
    """
    ns = state.node(node_id)
    if not certo:
        ns.previsoes_seguidas = 0
        ns.previsoes_desde = None
        return None

    ns.previsoes_seguidas += 1
    if ns.previsoes_desde is None:
        ns.previsoes_desde = hoje.isoformat()

    if ns.previsoes_seguidas < SEGUIDAS_PARA_AUTOMATICO:
        return None
    if ns.previsoes_desde >= hoje.isoformat():
        return None                      # ainda não sobreviveu a um intervalo
    if ns.dominio < Mastery.ESCRITO_SOZINHO:
        return None                      # prever não substitui ter escrito
    antes = ns.dominio
    ns.dominio = Mastery.AUTOMATICO
    ns.previsoes_seguidas = 0
    ns.previsoes_desde = None
    ns.visto_em = hoje.isoformat()
    return f"{node_id}: {antes.label} → {ns.dominio.label}"


def em_falta(state: State, node_id: str) -> int:
    return max(0, SEGUIDAS_PARA_AUTOMATICO - state.node(node_id).previsoes_seguidas)
